#!/usr/bin/env python3
"""Pre-renders the panel's text into small bitmap tables (payload/src/panel_font.cpp).
So the headset never needs a font file or a font library. Uses the free "Inter" font (SIL OFL)."""
import sys
from PIL import ImageFont

FONTS = [  # (c++ name, file, pixel size)
    ("kFontTitle",  "/usr/share/fonts/opentype/inter/Inter-Bold.otf",     54),
    ("kFontHead",   "/usr/share/fonts/opentype/inter/Inter-Bold.otf",     34),
    ("kFontLabel",  "/usr/share/fonts/opentype/inter/Inter-SemiBold.otf", 24),
    ("kFontSmall",  "/usr/share/fonts/opentype/inter/Inter-Medium.otf",   19),
    ("kFontTiny",   "/usr/share/fonts/opentype/inter/Inter-Medium.otf",   15),
]
FIRST, LAST = 32, 126
out = ['// GENERATED by tools/gen_font.py - do not edit by hand. Font: Inter (SIL Open Font License 1.1).',
       '#include "panel.h"', 'namespace tzpanel {', '']
for name, path, size in FONTS:
    f = ImageFont.truetype(path, size)
    asc, desc = f.getmetrics()
    alpha, glyphs = [], []
    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        adv = int(round(f.getlength(ch)))
        if ch == " ":
            glyphs.append((len(alpha), 0, 0, 0, 0, adv)); continue
        mask, off = f.getmask2(ch, mode="L", anchor="ls")   # off = where the mask's top-left sits vs the baseline origin
        mw, mh = mask.size
        if mw == 0 or mh == 0:
            glyphs.append((len(alpha), 0, 0, 0, 0, adv)); continue
        glyphs.append((len(alpha), mw, mh, int(off[0]), int(off[1]), adv))
        alpha.extend(list(mask))
    out.append(f'static const unsigned char {name}_alpha[] = {{')
    line = []
    for i, v in enumerate(alpha):
        line.append(str(v))
        if len(line) == 32: out.append(','.join(line) + ','); line = []
    if line: out.append(','.join(line))
    out.append('};')
    out.append(f'static const Glyph {name}_glyphs[] = {{')
    for g in glyphs: out.append('{%d,%d,%d,%d,%d,%d},' % g)
    out.append('};')
    out.append(f'const Font {name} = {{ {size}, {asc}, {asc+desc}, {name}_glyphs, {name}_alpha }};')
    out.append('')
out.append('}  // namespace tzpanel')
open(sys.argv[1], 'w').write('\n'.join(out) + '\n')
print("ok", sum(1 for _ in out), "lines")
